services:
  - type:  web
    name: neurotrace-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9